export const themes = {
  light: {
    name: "Light",
    colors: {
      background: "#ffffff",
      foreground: "#000000",
      card: "#ffffff",
      cardForeground: "#000000",
      primary: "#1877f2",
      primaryForeground: "#ffffff",
      secondary: "#f0f2f5",
      secondaryForeground: "#000000",
      muted: "#f0f2f5",
      mutedForeground: "#65676b",
      accent: "#1877f2",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#e4e6eb",
      input: "#e4e6eb",
      ring: "#1877f2",
    }
  },
  dark: {
    name: "Dark",
    colors: {
      background: "#18191a",
      foreground: "#e4e6eb",
      card: "#242526",
      cardForeground: "#e4e6eb",
      primary: "#2374e1",
      primaryForeground: "#ffffff",
      secondary: "#3a3b3c",
      secondaryForeground: "#e4e6eb",
      muted: "#3a3b3c",
      mutedForeground: "#b0b3b8",
      accent: "#2374e1",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#3a3b3c",
      input: "#3a3b3c",
      ring: "#2374e1",
    }
  },
  facebook: {
    name: "Facebook",
    colors: {
      background: "#f0f2f5",
      foreground: "#1c1e21",
      card: "#ffffff",
      cardForeground: "#1c1e21",
      primary: "#1877f2",
      primaryForeground: "#ffffff",
      secondary: "#e4e6eb",
      secondaryForeground: "#1c1e21",
      muted: "#e4e6eb",
      mutedForeground: "#65676b",
      accent: "#42b883",
      accentForeground: "#ffffff",
      destructive: "#f02849",
      destructiveForeground: "#ffffff",
      border: "#dadde1",
      input: "#f0f2f5",
      ring: "#1877f2",
    }
  },
  opensuse: {
    name: "openSUSE",
    colors: {
      background: "#173f4f",
      foreground: "#ffffff",
      card: "#35b9ab",
      cardForeground: "#ffffff",
      primary: "#73ba25",
      primaryForeground: "#ffffff",
      secondary: "#35b9ab",
      secondaryForeground: "#ffffff",
      muted: "#21a4a2",
      mutedForeground: "#ffffff",
      accent: "#73ba25",
      accentForeground: "#173f4f",
      destructive: "#ff6347",
      destructiveForeground: "#ffffff",
      border: "#35b9ab",
      input: "#21a4a2",
      ring: "#73ba25",
    }
  },
  nobara: {
    name: "Nobara",
    colors: {
      background: "#1a1a1a",
      foreground: "#ffffff",
      card: "#2d2d2d",
      cardForeground: "#ffffff",
      primary: "#ff6b6b",
      primaryForeground: "#ffffff",
      secondary: "#4a4a4a",
      secondaryForeground: "#ffffff",
      muted: "#3a3a3a",
      mutedForeground: "#cccccc",
      accent: "#ff6b6b",
      accentForeground: "#ffffff",
      destructive: "#ff4444",
      destructiveForeground: "#ffffff",
      border: "#4a4a4a",
      input: "#3a3a3a",
      ring: "#ff6b6b",
    }
  },
  windows: {
    name: "Windows 11",
    colors: {
      background: "#f3f3f3",
      foreground: "#000000",
      card: "#ffffff",
      cardForeground: "#000000",
      primary: "#0078d4",
      primaryForeground: "#ffffff",
      secondary: "#e5e5e5",
      secondaryForeground: "#000000",
      muted: "#f2f2f2",
      mutedForeground: "#5e5e5e",
      accent: "#0078d4",
      accentForeground: "#ffffff",
      destructive: "#d13438",
      destructiveForeground: "#ffffff",
      border: "#e5e5e5",
      input: "#ffffff",
      ring: "#0078d4",
    }
  },
  ubuntu: {
    name: "Ubuntu",
    colors: {
      background: "#2c001e",
      foreground: "#ffffff",
      card: "#5e2750",
      cardForeground: "#ffffff",
      primary: "#e95420",
      primaryForeground: "#ffffff",
      secondary: "#77216f",
      secondaryForeground: "#ffffff",
      muted: "#5e2750",
      mutedForeground: "#aea79f",
      accent: "#e95420",
      accentForeground: "#ffffff",
      destructive: "#df382c",
      destructiveForeground: "#ffffff",
      border: "#77216f",
      input: "#5e2750",
      ring: "#e95420",
    }
  }
}